language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    
cache:
  - cargo
  - directories:
    - capstone
    - python

env:
  - QT_SELECT=5

dist: trusty
sudo: required

install:
  - if git clone -b '3.0.5' --single-branch --depth 1 https://github.com/aquynh/capstone capstone; then
      pushd capstone;
        mkdir usr;
        PREFIX=./usr make install;
      popd;
    fi
  - if git clone -b 'v3.6.7' --single-branch --depth 1 https://github.com/python/cpython python; then
      pushd python;
        mkdir usr;
        ./configure --prefix="$PWD/usr";
        make;
        make install;
      popd;
    fi
  - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qt5-qmake

script:
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:~/capstone/usr/lib/"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:~/python/usr/lib/"
  - export PATH="$PATH:~/python/usr/bin/"
  - cargo build --verbose
  - pushd libllama
  - cargo test --verbose
  - popd
  - cargo test --verbose
