[package]
name = "llama"
version = "0.1.0"
authors = ["archshift <gh@archshift.com>"]

[[bin]]
name = "llama-cli"
path = "llama-cli/main.rs"

[dependencies]
capstone = "0.0"
env_logger = "0.3"
libc = "0.2"
libllama = { path = "libllama" }
log = "0.3"
sdl2 = "0.28"