[package]
name = "llama"
version = "0.1.0"
authors = ["archshift <gh@archshift.com>"]
build = "build.rs"

[[bin]]
name = "llama-ui"
path = "llama-ui/main.rs"

[dependencies]
capstone = "0.0"
lgl = { git = "https://github.com/archshift/lgl" }
libc = "0.2"
libllama = { path = "libllama" }
log = "0.3"